export const NEW_GAME_LOADING = "NEW_GAME_LOADING";
export const RESET_GAME = "RESET_GAME";
export const PLAYING_START = "PLAYING_START";
export const BOARD_UPDATE = "BOARD_UPDATE";

export const CELL_VALUE_CHANGED = "CELL_VALUE_CHANGED";
