export const NEW_GAME_LOADING = "NEW_GAME_LOADING";
export const RESET_GAME = "RESET_GAME";
export const PLAYING_STARTED = "PLAYING_STARTED";
export const PLAYING_STOPPED = "PLAYING_STOPPED";

export const CELL_VALUE_CHANGED = "CELL_VALUE_CHANGED";
